name: Build & test

on: push

jobs:

  build:
    strategy:
      fail-fast: false
      matrix:
        os:
        - ubuntu-latest
        - windows-latest
        - macOS-latest
        include:
        - os: ubuntu-latest
          target: x86_64-unknown-linux-musl
          flags: --target=x86_64-unknown-linux-musl

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2

    ### Submodule hackery

    - name: Initialize submodules
      run: git submodule update --init --recursive

    ### Prereqs

    - name: Linux - Install musl-tools
      if: runner.os == 'Linux'
      run: sudo apt-get install -y musl-tools
    
    - name: Add rustup target
      if: matrix.target
      run: rustup target add ${{ matrix.target }}

    ### Test

    - name: Test askalono
      run: cargo test --verbose --release ${{ matrix.flags }}

    - name: Test askalono-cli
      run: cargo test --verbose --release ${{ matrix.flags }}
      working-directory: cli
